title: s-mage's place
description: "That's my place to express thoughts when I have them. Mostly about programming."
permalink: /:year/:month/:day/:title.html
markdown: kramdown
gems:
  - jekyll-sitemap
